### ISSUE TITLE
Instrução incorreta: slli

### ISSUE THREAD

**Issue by EltonCN** [arRISCado/arRISCado#58]
Código de teste:

`slli a0, a0, 2`

Info | Valor
-- | --
a0 inicial | 0000 1000 0000 0000 0000 0000 0000 0000
a0 esperado | 0010 0000 0000 0000 0000 0000 0000 0000
a0 obtido | 0000 1000 0000 0000 0000 0000 0000 0010

**Comment by llTurtle22ll** [comment]
O PR #60 tem o intuito de resolver esse problema, dê uma olhada pra ver se ele funciona como esperado.
